(function(){'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={new:'Bildirildi',seen:'İşleme alındı',en_route:'Personel yolda',resolved:'Tamamlandı'},categories={door:'Kapı sorunu',stopped:'Asansör çalışmıyor',noise:'Ses / titreşim',lighting:'Aydınlatma',other:'Diğer'};
let client,user=null,apartments=[],current=null,reports=[],signup=false,recovery=false,epoch=0,busy=false,submitting=false,requestId=null,savedFault=null,lastFocus=null;
const uuid=()=>crypto.randomUUID?crypto.randomUUID():([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));
let invite='';try{const fragment=new URLSearchParams(location.hash.slice(1));const token=fragment.get('davet');if(token&&/^[a-f0-9]{64}$/.test(token)){sessionStorage.setItem('abrManagerInvite',token);history.replaceState(null,'',location.pathname+location.search);}invite=sessionStorage.getItem('abrManagerInvite')||'';}catch(e){}
try{recovery=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery';}catch(e){}
$('inviteNotice').hidden=!invite;
const phone=s=>String(s||'').replace(/[^+\d]/g,'');
function date(s,withTime=false){if(!s)return 'Bilgi paylaşılmadı';const d=new Date(s);return isNaN(d)?String(s):d.toLocaleString('tr-TR',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'long'});}
function errorText(e){const msg=String(e&&e.message||e||'İşlem tamamlanamadı.');if(/PGRST202|PGRST205|does not exist|schema cache/.test(msg))return 'Yönetici portalı henüz firma tarafından etkinleştirilmemiş.';if(/Failed to fetch|NetworkError|fetch failed/i.test(msg))return 'Bağlantı kurulamadı. İnternetinizi kontrol edip tekrar deneyin.';if(/Invalid login credentials/.test(msg))return 'E-posta veya şifre yanlış.';if(/Email not confirmed/.test(msg))return 'Giriş yapmadan önce e-posta adresinizi doğrulayın.';if(/rate limit|too many/i.test(msg))return 'Çok sık deneme yapıldı. Biraz sonra tekrar deneyin.';return msg.slice(0,250);}
function message(id,text,isError=true){const el=$(id);el.textContent=text;el.hidden=!text;el.classList.toggle('error',isError);}
async function rpc(name,args={}){const r=await client.rpc(name,args);if(r.error)throw r.error;return r.data;}
function resetDraft(){savedFault=null;requestId=null;['files','description','category','priority'].forEach(id=>$(id).disabled=false);$('faultForm').reset();}
function setAuth(){epoch++;user=null;current=null;apartments=[];reports=[];resetDraft();closeModal('reportModal');closeModal('detailModal');$('auth').hidden=false;$('app').hidden=true;$('bottom').hidden=true;$('logout').hidden=true;$('recovery').hidden=true;$('overview').replaceChildren();$('reports').replaceChildren();}
function authMode(value){signup=value;$('loginTab').classList.toggle('active',!signup);$('signupTab').classList.toggle('active',signup);$('authSubmit').textContent=signup?'Hesap oluştur':'Giriş yap';$('password').autocomplete=signup?'new-password':'current-password';message('authError','');}
async function load(){if(busy||!user||recovery||document.hidden)return;busy=true;const ticket=++epoch;try{
 if(invite){await rpc('abr_mgr_accept',{p_token:invite});if(ticket!==epoch)return;invite='';sessionStorage.removeItem('abrManagerInvite');$('inviteNotice').hidden=true;}
 const list=await rpc('abr_mgr_my_apartments');if(ticket!==epoch)return;
 const old=current&&current.id;apartments=Array.isArray(list)?list:[];current=apartments.find(a=>a.id===old)||apartments[0]||null;
 $('auth').hidden=true;$('recovery').hidden=true;$('app').hidden=false;$('logout').hidden=false;$('noAccess').hidden=!!current;$('bottom').hidden=!current;
 $('apartmentSelect').hidden=apartments.length<2;$('apartmentSelect').innerHTML=apartments.map(a=>'<option value="'+esc(a.id)+'">'+esc(a.snapshot.name)+'</option>').join('');if(current)$('apartmentSelect').value=current.id;
 if(!current){resetDraft();$('apartmentTitle').textContent='Apartmanım';$('hello').textContent='Merhaba';$('syncTime').textContent='';$('overview').replaceChildren();$('reports').replaceChildren();closeModal('reportModal');closeModal('detailModal');message('appError','');return;}
 renderOverview();await loadReports(ticket);message('appError','');
 }catch(e){if(ticket!==epoch)return;if(invite){message('authError',errorText(e));$('auth').hidden=false;$('logout').hidden=false;message('inviteNotice','Davet kabul edilemedi. Doğru hesapla giriş yaptığınızdan emin olun. Yeni davet için firmanızla iletişime geçin.',false);}else{message('appError',errorText(e));$('app').hidden=false;$('auth').hidden=true;$('bottom').hidden=true;}}finally{busy=false;}}
function renderOverview(){const s=current.snapshot||{};$('apartmentTitle').textContent=s.name||'Apartmanım';$('hello').textContent='Merhaba, '+(current.manager_name||'Yönetici');$('syncTime').textContent='Firma verisi güncellendi: '+date(current.updated_at,true);
 const last=s.last_maintenance;const lm=last?new Date(last):null,now=new Date(),thisMonth=lm&&!isNaN(lm)&&lm.getMonth()===now.getMonth()&&lm.getFullYear()===now.getFullYear();
 $('overview').innerHTML='<section class="card hero"><div class="hero-icon" aria-hidden="true"><svg class="icon" viewBox="0 0 24 24" fill="none"><rect x="5" y="4" width="14" height="17" rx="3" stroke="currentColor" stroke-width="1.8"/><path d="m8 12 2 2 5-5M9 2v4m6-4v4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></div><div class="eyebrow">Son bakım</div><div class="date">'+esc(date(last))+'</div><p class="muted" style="font-size:14px">'+(last?'Firmanızın paylaştığı son bakım tarihi.':'Firmanız henüz bakım tarihi paylaşmadı.')+'</p><span class="status">'+(thisMonth?'Bu ayın bakımı kaydedildi':'Bu aya ait tamamlanmış bakım bilgisi yok')+'</span></section><section class="card"><h2>Firma ve muayene</h2><div class="info-row"><span>Firma</span><b>'+esc(s.company||'—')+'</b></div><div class="info-row"><span>Muayene etiketi</span><b>'+esc(s.inspection_label||'Bilgi paylaşılmadı')+'</b></div><div class="info-row"><span>Sonraki muayene</span><b>'+esc(date(s.inspection_date))+'</b></div>'+(phone(s.phone)?'<a class="btn secondary block" style="margin-top:20px" href="tel:'+esc(phone(s.phone))+'">Firmayı ara</a>':'<p class="muted">Firma iletişim numarası henüz paylaşılmadı.</p>')+'</section>';
}
async function loadReports(ticket){if(!current)return;const id=current.id,list=await rpc('abr_mgr_fault_list',{p_apartment:id});if(ticket!==epoch||!current||current.id!==id)return;reports=Array.isArray(list)?list:[];renderReports();}
function renderReports(){const el=$('reports');el.replaceChildren();if(!reports.length){el.innerHTML='<div class="card empty">Henüz arıza bildirimi yok.<br>Bir sorun olduğunda aşağıdan bildirebilirsiniz.</div>';return;}reports.forEach(r=>{let b=document.createElement('button');b.type='button';b.className='report';b.innerHTML='<header><b>'+esc(categories[r.category]||'Arıza bildirimi')+'</b><span class="pill '+(r.status==='resolved'?'resolved':'')+'">'+esc(labels[r.status]||r.status)+'</span></header><p>'+esc(r.description)+'</p><small>'+esc(date(r.created_at,true))+' · #'+esc(r.id.slice(0,8).toUpperCase())+'</small>';b.addEventListener('click',()=>detail(r));el.appendChild(b);});}
function openModal(id){lastFocus=document.activeElement;$(id).hidden=false;document.body.style.overflow='hidden';$(id).querySelector('button').focus();}
function closeModal(id){if(!$(id))return;$(id).hidden=true;if($('reportModal').hidden&&$('detailModal').hidden){document.body.style.overflow='';if(lastFocus&&lastFocus.isConnected)lastFocus.focus();}}
async function detail(r){const ap=current.id,ticket=epoch;openModal('detailModal');$('detailTitle').textContent='Bildirim #'+r.id.slice(0,8).toUpperCase();$('detailBody').innerHTML='<p style="white-space:pre-wrap">'+esc(r.description)+'</p><span class="pill">'+esc(labels[r.status]||r.status)+'</span><ul class="timeline">'+(r.events||[]).map(e=>'<li><b>'+esc(labels[e.status]||e.status)+'</b>'+(e.note?'<p>'+esc(e.note)+'</p>':'')+'<time>'+esc(date(e.created_at,true))+'</time></li>').join('')+'</ul><div class="photos" id="detailPhotos"></div>';
 for(const p of r.photos||[]){const response=await client.storage.from('manager-photos').createSignedUrl(p.path,90);if(ticket!==epoch||!current||current.id!==ap||$('detailModal').hidden)return;if(response.error){const t=document.createElement('p');t.className='muted';t.textContent='Fotoğraf açılamadı. Bildirimi yeniden açmayı deneyin.';$('detailPhotos').appendChild(t);continue;}const img=document.createElement('img');img.src=response.data.signedUrl;img.alt='Arıza fotoğrafı';img.loading='lazy';$('detailPhotos').appendChild(img);}
}
async function compress(file){if(!file||!/^image\//.test(file.type)||file.size>20*1024*1024)throw new Error('Fotoğraflar 20 MB’dan küçük olmalı.');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Fotoğraf okunamadı. JPEG veya PNG olarak tekrar seçin.'));image.src=url;});const ratio=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*ratio));canvas.height=Math.max(1,Math.round(img.height*ratio));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));if(!blob||blob.size>2097152)throw new Error('Fotoğraf küçültülemedi. Daha küçük bir fotoğraf seçin.');return blob;}finally{URL.revokeObjectURL(url);}}
async function submitFault(event){event.preventDefault();if(submitting||!current)return;if(navigator.onLine===false){message('faultError','İnternet bağlantısı gerekli. Yazdığınız açıklama bu ekran açıkken korunur.');return;}const ap=current.id,description=$('description').value.trim(),files=Array.from($('files').files);if(description.length<10||files.length>4){message('faultError','En az 10 karakter açıklama ve en fazla 4 fotoğraf ekleyin.');return;}submitting=true;$('faultSubmit').disabled=true;$('reportClose').disabled=true;message('faultError','');try{
 // Validate/decode all photos before creating the report. request UUID makes network retries safe.
 const blobs=await Promise.all(files.map(compress));requestId=requestId||uuid();savedFault=savedFault||await rpc('abr_mgr_submit_fault',{p_apartment:ap,p_description:description,p_category:$('category').value,p_priority:$('priority').value,p_request:requestId});
 $('files').disabled=true;$('description').disabled=true;$('category').disabled=true;$('priority').disabled=true;
 if(!current||current.id!==ap)throw new Error('Apartman erişimi değişti.');
 for(let i=0;i<blobs.length;i++){if(savedFault.uploaded&&savedFault.uploaded.has(i))continue;const path=ap+'/'+savedFault.id+'/'+uuid()+'.jpg';const upload=await client.storage.from('manager-photos').upload(path,blobs[i],{contentType:'image/jpeg',upsert:false});if(upload.error)throw upload.error;try{await rpc('abr_mgr_attach_photo',{p_fault:savedFault.id,p_path:path});}catch(e){await client.storage.from('manager-photos').remove([path]);throw e;}if(!savedFault.uploaded)savedFault.uploaded=new Set();savedFault.uploaded.add(i);}
 savedFault=null;requestId=null;['files','description','category','priority'].forEach(id=>$(id).disabled=false);$('faultForm').reset();closeModal('reportModal');await load();
 }catch(e){message('faultError',(savedFault?'Bildiriminiz kaydedildi; bazı fotoğraflar gönderilemedi. Tekrar basınca yalnız eksik fotoğraflar denenir. ':'')+errorText(e));}finally{submitting=false;$('faultSubmit').disabled=false;$('reportClose').disabled=false;}}
async function init(){if(!window.supabase){message('authError','Giriş bileşeni yüklenemedi. İnternetinizi kontrol edip sayfayı yenileyin.');$('authSubmit').disabled=true;return;}
 client=window.supabase.createClient('https://vfadlxuujqcpkckvwjbl.supabase.co','sb_publishable_QvEWbZy98j_kUKd7rPp0ew_e4J2GqKQ',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'abr-manager-auth-v1'}});
 client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(event==='PASSWORD_RECOVERY'){recovery=true;user=session&&session.user;$('auth').hidden=true;$('app').hidden=true;$('bottom').hidden=true;$('recovery').hidden=false;return;}if(!session){setAuth();return;}if(user&&user.id!==session.user.id)setAuth();user=session.user;if(!recovery)load();},0);});
 const session=await client.auth.getSession();if(session.error){message('authError',errorText(session.error));return;}if(session.data.session){user=session.data.session.user;await load();}
}
$('loginTab').addEventListener('click',()=>authMode(false));$('signupTab').addEventListener('click',()=>authMode(true));
$('authForm').addEventListener('submit',async e=>{e.preventDefault();if($('authSubmit').disabled)return;$('authSubmit').disabled=true;message('authError','');try{const email=$('email').value.trim(),password=$('password').value;const result=signup?await client.auth.signUp({email,password,options:{emailRedirectTo:new URL('yonetici.html',location.href).href}}):await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;$('password').value='';if(!result.data.session)message('authError','Doğrulama bağlantısı e-postanıza gönderildi. Adresinizi doğruladıktan sonra bu davet bağlantısından giriş yapın.',false);else{user=result.data.session.user;await load();}}catch(error){message('authError',errorText(error));}finally{$('authSubmit').disabled=false;}});
$('forgot').addEventListener('click',async()=>{const email=$('email').value.trim();if(!$('email').checkValidity()){message('authError','Önce e-posta adresinizi yazın.');return;}$('forgot').disabled=true;try{const r=await client.auth.resetPasswordForEmail(email,{redirectTo:new URL('yonetici.html',location.href).href});if(r.error)throw r.error;message('authError','Şifre yenileme bağlantısı e-postanıza gönderildi.',false);}catch(e){message('authError',errorText(e));}finally{$('forgot').disabled=false;}});
$('recoveryForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const r=await client.auth.updateUser({password:$('newPassword').value});if(r.error)throw r.error;recovery=false;$('newPassword').value='';await load();}catch(e){alert(errorText(e));}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{if(submitting)return;const r=await client.auth.signOut({scope:'local'});if(r.error){message('appError',errorText(r.error));return;}recovery=false;setAuth();});
$('refresh').addEventListener('click',load);$('apartmentSelect').addEventListener('change',async e=>{if(submitting)return;epoch++;current=apartments.find(a=>a.id===e.target.value)||null;reports=[];renderReports();savedFault=null;requestId=null;['files','description','category','priority'].forEach(id=>$(id).disabled=false);$('faultForm').reset();closeModal('reportModal');closeModal('detailModal');if(current){renderOverview();await loadReports(epoch);}});
$('reportOpen').addEventListener('click',()=>{if(!current)return;const p=phone(current.snapshot.phone);$('emergencyCall').removeAttribute('href');if(p)$('emergencyCall').href='tel:'+p;openModal('reportModal');});$('reportClose').addEventListener('click',()=>{if(!submitting)closeModal('reportModal');});$('detailClose').addEventListener('click',()=>closeModal('detailModal'));$('faultForm').addEventListener('submit',submitFault);
$('files').addEventListener('change',()=>{if(savedFault){message('faultError','Eksik fotoğraf gönderimini tamamlayana kadar seçili fotoğrafları değiştirmeyin.');return;}$('fileInfo').textContent=$('files').files.length+' fotoğraf seçildi · en fazla 4';});
window.addEventListener('online',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(()=>{if(!submitting&&$('reportModal').hidden&&$('detailModal').hidden)load();},30000);
document.addEventListener('keydown',e=>{const modal=!$('reportModal').hidden?$('reportModal'):!$('detailModal').hidden?$('detailModal'):null;if(!modal)return;if(e.key==='Escape'&&!submitting){closeModal(modal.id);return;}if(e.key==='Tab'){const items=Array.from(modal.querySelectorAll('button,input,select,textarea,a[href]')).filter(n=>!n.disabled);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
init().catch(e=>message('authError',errorText(e)));
})();
